// Phone markup retained verbatim from the reference prototype.
export function templates(phase){
const phoneBtn=(label,action,alt=false)=>`<button class="phone-button ${alt?'alt':''}" data-action="${action}">${label}</button>`;
return {checkout:'landing',accountMode:'signup',option:0,cursor:0,subscribed:false,games:["Jeopardy!","Song Quiz","Wheel of Fortune","Guess the Emoji","Werds Pur Minite","Sketchy AF","Spot On","Wit’s End","CoComelon Sing & Play","Weekend Poker","Discat Hero","Bingo","Twenty Questions","Karaoke","Game 15 · Preview","Game 16 · Preview","Game 17 · Preview","Game 18 · Preview","Game 19 · Preview","Game 20 · Preview"],
dpad(){return `<div class="dpad" aria-label="TV navigation"><button data-action="pad" data-dir="up" aria-label="Up">▲</button><button data-action="pad" data-dir="left" aria-label="Left">◀</button><button data-action="pad" data-dir="select" aria-label="Select game">OK</button><button data-action="pad" data-dir="right" aria-label="Right">▶</button><button data-action="pad" data-dir="down" aria-label="Down">▼</button></div>`},
phoneChrome(content,skippable=true){return `${skippable?'<button class="phone-skip" data-action="skip-trial">Skip</button>':''}<p class="phone-logo"><img src="assets/weekend-3d-yellow.svg" alt="Weekend"></p>${content}`},
claimPhone(){
    if(this.checkout==='landing')return this.phoneChrome(`<div class="offer-orbit">20</div><p class="state-pill">ONE SUBSCRIPTION</p><h3 class="phone-title offer-title">Every game night.<br>All in one place.</h3><p class="phone-copy">Play all 20 Weekend games free for one week.</p>${phoneBtn('Claim My Free Week','begin-signup')}<p class="offer-terms">Then $12.99/month. Cancel anytime.<br>Prototype—no trial or charge starts.</p>`);
    if(this.checkout==='account')return this.phoneChrome(`<p class="state-pill">${this.accountMode==='signup'?'CREATE YOUR ACCOUNT':'WELCOME BACK'}</p><h3 class="phone-title">${this.accountMode==='signup'?'Save your game nights.':'Sign in to Weekend.'}</h3><div class="social-stack">${phoneBtn('Continue with Apple','account-complete')}${phoneBtn('Continue with Google','account-complete',true)}</div><div class="or-rule"><span>or</span></div><label class="email-label" for="prototypeEmail">Email</label><input class="email-input" id="prototypeEmail" type="email" placeholder="you@example.com" autocomplete="off">${phoneBtn('Continue with Email','account-complete')}<button class="account-switch" data-action="switch-account">${this.accountMode==='signup'?'Already have an account? Sign In':'New to Weekend? Create Account'}</button>`);
    if(this.checkout==='offer')return this.phoneChrome(`<p class="state-pill">YOUR FREE WEEK</p><h3 class="phone-title offer-title">All 20 games.<br>$0 today.</h3><div class="price-card"><strong>7 days free</strong><span>Then $12.99/month</span><span>Cancel anytime</span></div>${phoneBtn('Start Free Trial','open-apple-pay')}<p class="offer-terms">Subscription renews automatically until canceled.<br>Prototype—no trial or charge starts.</p>`);
    return this.phoneChrome(`<p class="state-pill">APPLE PAY · DEMO</p><div class="apple-sheet"><div class="apple-pay-mark">Pay</div><div class="pay-row"><span>Weekend Monthly</span><strong>$12.99 after trial</strong></div><div class="pay-row"><span>Due today</span><strong>$0.00</strong></div><button class="apple-confirm" data-action="confirm-payment">Confirm · Demo</button></div><button class="account-switch" data-action="back-to-offer">Cancel</button>`,false)
  },
controllerPhone(){return `<p class="phone-logo"><img src="assets/weekend-3d-yellow.svg" alt="Weekend"></p><p class="state-pill">TV CONTROLLER · DEMO</p><h3 class="phone-title">You’re in control.</h3>${this.dpad()}<p class="phone-selection">${phase===7?(this.option===0?'Sign In on Your Phone':'See All Games'):this.games[this.cursor]}</p><button class="account-switch" data-action="remote-back">← Back</button>`},
hubPhone(){return this.controllerPhone()+`<p class="membership-chip">${this.subscribed?'✓ Weekend Member · Demo':'Browse freely · Membership to play'}</p>`},
successPhone(){return `<p class="phone-logo"><img src="assets/weekend-3d-yellow.svg" alt="Weekend"></p><div class="phone-success-check">✓</div><p class="state-pill">MEMBERSHIP STARTED · DEMO</p><h3 class="phone-title offer-title">Game night<br>is unlocked.</h3><p class="phone-copy">Your free week is ready. Explore all 20 games.</p>${phoneBtn('Browse All Games','browse-after-success')}`}
};}
